---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['OMNIBUS_CHEF_CLIENT_VERSION'] || 'latest' %>

verifier:
  name: inspec

platforms:
  - name: windows2008r2
  - name: windows2012r2

suites:
  - name: default
    run_list:
      - recipe[sbp_messageanalyzer::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
